// Main wizard component
export { default as PromptWizard } from './PromptWizard'

// Step components
export { default as TemplateSelectionStep } from './steps/TemplateSelectionStep'
export { default as CustomInputStep } from './steps/CustomInputStep'
export { default as AIGenerationStep } from './steps/AIGenerationStep'

// Types
export type {
  WizardStep,
  PromptTemplate,
  TemplateField,
  FormData,
  GeneratedPrompt,
  WizardState,
  WizardActions
} from './types'

// Utility functions
export const validateTemplateField = (field: any, value: any): string => {
  if (field.required && (!value || value === '')) {
    return `${field.label} is required`
  }
  return ''
}

export const generatePromptId = (): string => {
  return `prompt_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`
}

export const formatPromptForDownload = (prompt: any): string => {
  return `# ${prompt.title}

Generated on: ${prompt.createdAt.toLocaleString()}
Template: ${prompt.template.title}
Industry: ${prompt.template.industry}

## Content

${prompt.content}

---

Generated by AI Prompt Generator Pro
`
}